Pull request #1289: add master branch release
Merge in DTX/import-api-rdc from REL-793725-change-releases-to-master-branch to master

Squashed commit of the following:

commit ecf918a31851226680e6dfda7f6f36b45a50d680
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Tue Jan 10 12:54:56 2023 +0100

    fix broken script

commit bbf6443b95c0e7def9b8d8a5a005d30b1c3bc309
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Tue Jan 10 12:46:02 2023 +0100

    remove conditions this PR branch as master

commit a5ef14c77b0458a891d434d5b037d3a4c8db7b59
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Tue Jan 10 10:38:29 2023 +0100

    revert change

commit 9cec87fdf816091dbb7dc48a3bb76d0a11d4c005
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Tue Jan 10 10:34:37 2023 +0100

    change releases name to be Monthly Releases

commit 4de0f43f93f253693c7298ee6cb6eec330bc78f8
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Mon Jan 9 13:55:30 2023 +0100

    remove master branch from condition checking version in branch name

commit f57bc00c94ba7b274a06a638a96e65fda8ee9b89
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Mon Jan 9 13:40:37 2023 +0100

    update error message for cases when no sdk and rdc publish is done

commit 36ef7ffa70da319ac19981048ab5deebd896f653
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Mon Jan 9 13:39:34 2023 +0100

    change team email address and subject to HDA from TGTBTU

commit 54cdcd314f03c99e287ded7b79ccef81bb80550b
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Mon Jan 9 13:38:32 2023 +0100

    update SUT template to aio-zarzaparrilla-0

commit 88b26b6bf27a2343ed94eda0257110e4f9819bda
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Mon Jan 9 13:37:46 2023 +0100

    change develop to master in pipelines

commit 6ce9000ac93f17362f17029d5d121f4ad4ea2c1f
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Mon Jan 9 13:36:17 2023 +0100

    add master branch as condition for release branches
    change Einstein subpage name to Releases (instead of Master)

commit 9f26147b4bc5b135c139a10897641d1f82a03feb
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Mon Jan 9 13:34:32 2023 +0100

    add temporary PR branch for tests

commit 3d557b4b4f9c4aa60c332814f1ec4c2b5d99e0ba
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Thu Jan 5 18:14:59 2023 +0100

    add more changes to build scripts

commit 68bd72a458b3f51477886a8bfa274930aef907fa
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Thu Jan 5 17:12:40 2023 +0100

    update einstein template and script

commit 8e3f1ef4e97dc041830d56387d8f9aa35d4068bc
Author: Sylwester Pena <sylwester.pena@relativity.com>
Date:   Thu Jan 5 16:13:37 2023 +0100

    add master branch release

diff --git a/Tridentfile b/Tridentfile
--- a/Tridentfile
+++ b/Tridentfile
@@ -9,7 +9,7 @@ properties([
         choice(defaultValue: 'DEV',choices: ["DEV", "GOLD - RDC AND SDK", "GOLD - RDC ONLY", "GOLD - SDK ONLY"], description: "Choose your build type, only gold can produce production packages.", name: 'buildType'),
         choice(defaultValue: 'Release', choices: ["Release","Debug"], description: 'Build config', name: 'buildConfig'),
         choice(defaultValue: 'normal', choices: ["quiet", "minimal", "normal", "detailed", "diagnostic"], description: 'Build verbosity', name: 'buildVerbosity'),
-        string(defaultValue: '', description: 'Relativity branch to test against, leave null for latest hopper image', name: 'relativityBranch'),
+        string(defaultValue: 'current', description: 'Relativity branch to test against, leave current for version installed on hopper image', name: 'relativityBranch'),
         booleanParam(defaultValue: true, description: "Enable or disable running unit tests", name: 'runUnitTests'),
         booleanParam(defaultValue: true, description: "Enable or disable running integration tests", name: 'runIntegrationTests'),
         booleanParam(defaultValue: true, description: "Enable or disable creating a code coverage report", name: 'createCodeCoverageReport'),
@@ -33,23 +33,27 @@ if(branchName.startsWith('PR-'))
     branchName = env.CHANGE_BRANCH
 }
 def isReleaseBranch = branchName.startsWith('release-')
+// TODO - remove REL- after tests
+def isMasterBranch = branchName.startsWith('master')
+def isReleaseOrMasterBranch = isReleaseBranch || isMasterBranch
 def isGoldBuild = (params.buildType != 'DEV')
-def publishToRelease = (isGoldBuild && isReleaseBranch)
-def publishRdc =(!isReleaseBranch || (isReleaseBranch && params.buildType == 'GOLD - RDC AND SDK')|| (isReleaseBranch && params.buildType == 'GOLD - RDC ONLY'))
-def publishSdk =(!isReleaseBranch || (isReleaseBranch && params.buildType == 'GOLD - RDC AND SDK')|| (isReleaseBranch && params.buildType == 'GOLD - SDK ONLY'))
+def publishToRelease = (isGoldBuild && isReleaseOrMasterBranch)
+def publishRdc =(!isReleaseOrMasterBranch || (isReleaseOrMasterBranch && params.buildType == 'GOLD - RDC AND SDK')|| (isReleaseOrMasterBranch && params.buildType == 'GOLD - RDC ONLY'))
+def publishSdk =(!isReleaseOrMasterBranch || (isReleaseOrMasterBranch && params.buildType == 'GOLD - RDC AND SDK')|| (isReleaseOrMasterBranch && params.buildType == 'GOLD - SDK ONLY'))
 def publishSdkAndRdc = (publishSdk && publishRdc)
 build = params.build
 
 // On release branches tests should be executed against newest Relativity version from specified folder in \\bld-pkgs\Packages\Relativity\
 // Example: relativityBranch = 'release-11.3-mayapple' for branchName = 'release-1.11-mayapple'
-if(isReleaseBranch && (relativityBranch == null || relativityBranch.isEmpty()))
+// Example: relativityBranch = 'current' for relativity version installed on hopper - specific version installation is not performed
+if(isReleaseOrMasterBranch && (relativityBranch == null || relativityBranch.isEmpty()))
 {
 	currentBuild.result = 'FAILED' 
 	throw new Exception("Build failed because relativity installer source folder 'relativityBranch' is not defined in the script")
 }
 
 def config = [
-	sutTemplate: "aio-yarrow-eau",
+	sutTemplate: "aio-zarzaparrilla-0",
 	hopperApiUrl: "https://api.hopper.relativity.com/",
 	hopperApiUsername: "homeimprovement@relativity.com"
 ]
@@ -100,7 +104,7 @@ timestamps
                 {					
                     stage('Retrieve version')
                     {
-                        echo "Is release branch = $isReleaseBranch"
+                        echo "Is release branch = $isReleaseOrMasterBranch"
                         echo "Run integration tests = ${shouldRunIntegrationTests}"
                         echo "Is gold build = $isGoldBuild"
                         echo "Publishing to release? $publishToRelease"
@@ -404,7 +408,7 @@ timestamps
 						}
 						else
 						{
-						    echo "We can't create a release page as this needs a gold build of SDK and RDC to be created on release branch."
+						    echo "We can't create a release page as this needs a gold build of SDK and RDC to be created on release or master branch."
 						}
 					}
                 }
@@ -444,7 +448,7 @@ timestamps
             {
                 echo err.toString()
                 currentBuild.result = 'FAILED' 
-                if (branchName == 'develop' || isReleaseBranch)
+                if (branchName == 'develop' || isReleaseOrMasterBranch)
                 {
                     tools.sendEmailAboutFailureToTeam(branchName)
                 }
